name: Sync Upstream PR from Jazzmin

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Upstream PR number to merge (e.g. 635)'
        required: true
        type: string

jobs:
  sync-upstream-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/farridav/django-jazzmin.git
          git fetch upstream

      - name: Fetch and overwrite merge branch
        run: |
          git fetch upstream pull/${{ github.event.inputs.pr_number }}/head:merge-pr-${{ github.event.inputs.pr_number }}
          git branch -D merge-pr-${{ github.event.inputs.pr_number }} || true
          git checkout -b merge-pr-${{ github.event.inputs.pr_number }} FETCH_HEAD
          git push -f origin merge-pr-${{ github.event.inputs.pr_number }}

      - name: Create pull request into main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: "Sync upstream PR #${{ github.event.inputs.pr_number }}"
          body: |
            This pull request brings in upstream [PR #${{ github.event.inputs.pr_number }}](https://github.com/farridav/django-jazzmin/pull/${{ github.event.inputs.pr_number }}).

            Please review and merge if it passes your tests.
          head: merge-pr-${{ github.event.inputs.pr_number }}
          base: main
